### PR TITLE
Add 1.19.3 + updated mappings

### PR DESCRIPTION
**Pull request by kada49**
- added support for 1.19.3 forge + fabric
- updated fabric loader version
- updated forge versions to resemble the recommended version on their website
- updated most mcp mappings to the stable version (tested if building works)
- updated yarn mappings build version

### CODE REVIEW

**Comment by DJtheRedstoner** [comment]
The idea behind revisions is that once they have been created, the versions remain fixed (other than adding new mc versions). You should create a new revision for these changes. Additionally, some forge versions (I believe this is limited to the newest 1.12.2 builds) aren't compatible with `gg.essential.loom`, so updating them would actually break things.

**Comment by kada49** [comment]
For the first part of the message: ok I understand this for the yarn mappings that seem to update more often, but for the forge mappings I wanted to have stable ones instead of snapshots for "better" mappings once and for all.
For the second part of the message: do tou maybe know from what version upwards?

**Comment by Johni0702** [comment]
> do tou maybe know from what version upwards?

It's the 1.12.2 versions that officially use ForgeGradle 3 instead of 2.3, that's 14.23.5.2851 and up.

> ok I understand this for the yarn mappings that seem to update more often, but for the forge mappings I wanted to have stable ones instead of snapshots for "better" mappings once and for all.

You can have those, they just need to be defined in a newer revision so people that already set `essential.defaults.loom` to 0 in their build can continue to update EGT without breaking their build, and new people as well as those that explicitly want to update can set it to 1 to get the better stuff.
Here, I cherry-picked your commits and modified them such that they do that: 6f45d9b

> [add .idea folder to .gitignore](https://github.com/EssentialGG/essential-gradle-toolkit/pull/9/commits/5dcdd7c70cf1521bb2e9b80d1c9931da6fac8716)

This imo does not belong into the repo itself. There's countless editors and this project isn't strictly speaking tied to any of them. Instead I'd recommend setting up a global gitignore on your system that contains the files for the editor(s) you use: https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

**Comment by kada49** [comment]
Didn't know the global .gitignore even existed, Thank you!

**Pull request closed without merging**
